using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YouTubeAPI;

namespace dotnet_YouTubeAPI.Tests
{
    /// <summary>
    /// Represents Tracks table which contains main information about youtube video.
    /// </summary>
    public class TrackMock
    {

        /// <summary>
        /// Gets or sets unique VideoID of the track in table. Represents primary key in Tracks table. Contains unique string generated by YouTube.
        /// </summary>
        [Key]
        public string VideoId { get; set; }

        /// <summary>
        /// Gets or sets Title of the track.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets Channel Title on which Video was uploaded.
        /// </summary>
        public string ChannelTitle { get; set; }

        /// <summary>
        /// Gets or Sets YouTube Channel ID.
        /// </summary>
        public string ChannelId { get; set; }

        /// <summary>
        /// Gets or Sets YouTube video description.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets YouTube video release date.
        /// </summary>
        public DateTime ReleaseDate { get; set; }

        /// <summary>
        /// Gets or Sets URL for medium video thumbnail.
        /// </summary>
        public string ThumbnailMedium { get; set; }
        public DateTime SubscribeTime { get; set; }

        /// <summary>
        /// Connection to many entries in TracksHistory table which represents one to many relationship.
        /// </summary>
        public virtual ICollection<TracksHistory> TracksHistory { get; set; }

        /// <summary>
        /// Non-parametric construcor for Track class.
        /// </summary>
        public TrackMock() { }

        /// <summary>
        /// Contructor for Track class. Creates new instance of Track class which represents one entry in Tracks table.
        /// </summary>
        /// <param name="Id">Youtube video ID.</param>
        public TrackMock(string Id)
        {
            VideoId = Id;
            GetViedoData();
        }

        public void GetViedoData()
        {
            Title = "Mock Title";
            ChannelTitle = "Mock Channel Title";
            ChannelId = "Mock Channel Id";
            Description = "Mock Description";
            ReleaseDate = new DateTime(2023, 07, 05, 12, 00, 00);
            ThumbnailMedium = "Mock Thumbnail Url";
            SubscribeTime = new DateTime(2023, 07, 05, 21, 37, 00);
        }
    }
}
